name: Build & Publish FE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env
        run: |
          cat <<EOF > .env
          VITE_API_SERVER_URL=${{ secrets.VITE_API_SERVER_URL }}
          VITE_AUTHENTICATION_SERVER_URL=${{ secrets.VITE_AUTHENTICATION_SERVER_URL }}
          VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_SOCKET_SERVER_URL=${{ secrets.VITE_SOCKET_SERVER_URL }}
          EOF

      - name: Create .env.production
        run: |
          cat <<EOF > .env.production
          VITE_API_SERVER_URL=${{ secrets.VITE_API_SERVER_URL }}
          VITE_AUTHENTICATION_SERVER_URL=${{ secrets.VITE_AUTHENTICATION_SERVER_URL }}
          VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_SOCKET_SERVER_URL=${{ secrets.VITE_SOCKET_SERVER_URL }}
          EOF

      - name: Install deps & Build
        run: |
          npm ci
          npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/image-converter-fe:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/image-converter-fe:${{ github.run_number }}
